import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/shared/ThemeProvider";
import { Client } from "appwrite";
const client = new Client();


const projectID = process.env.APPWRITE_PROJECT_ID || '';
const endpoint = process.env.APPWRITE_ENDPOINT || '';
client
  .setEndpoint(endpoint)
  .setProject(projectID);



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

const raleWay = Raleway({
  subsets: [
    "latin",
  ]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleWay.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
        // disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html >
  );
}
